name: Run Tests

on:
  push:
    branches: [main]
  pull_request:  

jobs:
  microservice-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Install Docker
        run: |
          docker --version
      - name: Debug structure
        run: |
          pwd
          ls -R docker-projects/MicroService-Demo
      - name: Check Dockerfiles
        run: |
          ls docker-projects/MicroService-Demo/backend
          ls docker-projects/MicroService-Demo/frontend
          ls docker-projects/MicroService-Demo/tests
      - name: Build and Run Tests
        working-directory: docker-projects/MicroService-Demo
        run: |      
          docker compose up --build --abort-on-container-exit
      - name: Cleanup
        working-directory: docker-projects/MicroService-Demo
        run: docker compose down -v

  parabank-bdd-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@4

      - name: Build Docker image
        working-directory: docker-projects/Parabank-BDD
        run: |
          docker build -t parabank-bdd .

      - name: Run Tests
        working-directory: docker-projects/Parabank-BDD
        run: |
          mkdir -p reports
          docker run --rm \
            -v ${{ github.workspace }}/docker-projects/Parabank-BDD/reports:/app/reports \
            parabank-bdd

      - name: Generate HTML reports
        working-directory: docker-projects/Parabank-BDD
        run: |
          node reports/report.js
      
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: parabank-bdd-report
          path: docker-projects/Parabank-BDD/reports