name: Run Tests

on:
  push:
    branches: [main]
  schedule:  
    - cron: '0 0 * * *' #nightly

permissions:
  contents: write
  
jobs:
  microservice-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Install Docker
        run: |
          docker --version
      - name: Debug structure
        run: |
          pwd
          ls -R docker-projects/MicroService-Demo
      - name: Check Dockerfiles
        run: |
          ls docker-projects/MicroService-Demo/backend
          ls docker-projects/MicroService-Demo/frontend
          ls docker-projects/MicroService-Demo/tests
      - name: Build and Run Tests
        working-directory: docker-projects/MicroService-Demo
        run: |      
          docker compose up --build --abort-on-container-exit
      - name: Cleanup
        working-directory: docker-projects/MicroService-Demo
        run: docker compose down -v

  parabank-bdd-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        working-directory: docker-projects/Parabank-BDD
        run: npm install

      - name: Build Docker image
        working-directory: docker-projects/Parabank-BDD
        run: |
          docker build -t parabank-bdd .

      - name: Run Tests
        working-directory: docker-projects/Parabank-BDD
        run: |
          mkdir -p reports
          if["${{ github.event_name }}" = "schedule"]; then
          echo "Running full suite..."
          docker run --rm \
            -v ${{ github.workspace }}/docker-projects/Parabank-BDD/reports:/app/reports \
            -e APP_URL=${{ secrets.PARABANK_BDD_BASE_URL }} \
            -e APP_USERNAME=${{ secrets.PARABANK_BDD_USERNAME }} \
            -e APP_PASSWORD=${{ secrets.PARABANK_BDD_PASSWORD }} \
            parabank-bdd
            else
            echo "Running smoke tests..."
            docker run --rm \
            -v ${{ github.workspace }}/docker-projects/Parabank-BDD/reports:/app/reports \
            -e APP_URL=${{ secrets.PARABANK_BDD_BASE_URL }} \
            -e APP_USERNAME=${{ secrets.PARABANK_BDD_USERNAME }} \
            -e APP_PASSWORD=${{ secrets.PARABANK_BDD_PASSWORD }} \
            parabank-bdd -- --tags "@smoke"
            fi

      - name: Generate HTML reports
        if: always()
        working-directory: docker-projects/Parabank-BDD
        run: |
          node reports/report.js
      
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parabank-bdd-report
          path: docker-projects/Parabank-BDD/reports

      - name: Deploy report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docker-projects/Parabank-BDD/reports/html-report